version: '3.7'

services:
  bot:
    build: 
      context: bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - bot-network
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - bot-network
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27027:27017"
    env_file:
      - .env
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - bot-network
    command: mongod --wiredTigerCacheSizeGB 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge