version: '3.7'

services:
  bot:
    build: 
      context: bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=False
      - MONGODB_HOST=mongodb
    networks:
      - bot-network
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/xumotjbot
    ports:
      - "8000:8000"
    volumes:
      - ./admin/static:/app/static
    networks:
      - bot-network
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    env_file:
      - .env
    networks:
      - bot-network
    command: mongod --wiredTigerCacheSizeGB 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

networks:
  bot-network:
    driver: bridge
